import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/toaster"
 

const font = Poppins({ weight:["200","300","400","500","600","700","800","900"],subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
         
        <main  > 
        {children}
        </main>
      <Toaster />
      </body>
    </html>
  )
}
